from __future__ import annotations

import socket

import pytest
from fastapi.testclient import TestClient

from pi_agent.handlers import network
from pi_protocol import AuthRequestPayload, Envelope, MessageType, NetworkInfoPayload

from .conftest import TOKEN

# Raspberry Pi OS Bookworm with both Ethernet and Wi-Fi up: two default routes,
# and the lower metric is the one traffic actually takes.
PROC_ROUTE = """\
Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\t\tMTU\tWindow\tIRTT
eth0\t00000000\t0102A8C0\t0003\t0\t0\t100\t00000000\t0\t0\t0
eth0\t0002A8C0\t00000000\t0001\t0\t0\t100\t00FFFFFF\t0\t0\t0
wlan0\t00000000\tFE02A8C0\t0003\t0\t0\t600\t00000000\t0\t0\t0
"""

PROC_WIRELESS = """\
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
 wlan0: 0000   57.  -53.  -256        0      0      0      0     36        0
"""

IW_LINK = """\
Connected to b4:fb:e4:aa:bb:cc (on wlan0)
\tSSID: Ev Agi 5G
\tfreq: 5180
\tRX: 8123456 bytes (9001 packets)
\tsignal: -47 dBm
\ttx bitrate: 390.0 MBit/s
"""


def _authenticated(client: TestClient):
    ws = client.websocket_connect("/ws").__enter__()
    ws.send_json(
        Envelope(type=MessageType.AUTH_REQUEST, payload=AuthRequestPayload(token=TOKEN)).model_dump(mode="json")
    )
    assert ws.receive_json()["type"] == MessageType.AUTH_OK.value
    return ws


# --- /proc/net/route --------------------------------------------------------


def test_default_gateway_decodes_little_endian_hex() -> None:
    assert network.parse_default_gateway(PROC_ROUTE) == "192.168.2.1"


def test_default_gateway_prefers_the_lowest_metric() -> None:
    """Ethernet (metric 100) beats Wi-Fi (600) - the same choice the kernel makes."""
    reversed_metrics = PROC_ROUTE.replace("\t100\t00000000", "\t900\t00000000", 1)
    assert network.parse_default_gateway(reversed_metrics) == "192.168.2.254"


def test_default_gateway_is_empty_without_a_route() -> None:
    assert network.parse_default_gateway("") == ""
    assert network.parse_default_gateway(PROC_ROUTE.splitlines()[0]) == ""


def test_default_gateway_ignores_on_link_routes() -> None:
    """The subnet route has no gateway flag; reporting 0.0.0.0 would be wrong."""
    on_link_only = "\n".join(PROC_ROUTE.splitlines()[:1] + [PROC_ROUTE.splitlines()[2]])
    assert network.parse_default_gateway(on_link_only) == ""


# --- resolv.conf ------------------------------------------------------------


def test_resolv_conf_collects_nameservers_and_drops_comments() -> None:
    text = "# Generated by NetworkManager\nnameserver 192.168.2.1\nnameserver 1.1.1.1  # yedek\n"
    assert network.parse_resolv_conf(text) == ["192.168.2.1", "1.1.1.1"]


def test_resolv_conf_deduplicates() -> None:
    assert network.parse_resolv_conf("nameserver 1.1.1.1\nnameserver 1.1.1.1\n") == ["1.1.1.1"]


def test_resolv_conf_ignores_other_directives() -> None:
    assert network.parse_resolv_conf("search lan\noptions edns0\n") == []


# --- wireless ---------------------------------------------------------------


def test_wireless_interfaces_skips_the_two_header_lines() -> None:
    assert network.parse_wireless_interfaces(PROC_WIRELESS) == ["wlan0"]


def test_wireless_interfaces_empty_on_a_wired_only_pi() -> None:
    assert network.parse_wireless_interfaces("\n".join(PROC_WIRELESS.splitlines()[:2])) == []


def test_iw_link_extracts_ssid_with_spaces_and_signal() -> None:
    assert network.parse_iw_link(IW_LINK) == ("Ev Agi 5G", -47)


def test_iw_link_reports_nothing_when_unassociated() -> None:
    assert network.parse_iw_link("Not connected.") == ("", None)


# --- collection / handler ---------------------------------------------------


def test_collect_interfaces_reports_the_local_machine() -> None:
    interfaces = network.collect_interfaces()
    assert interfaces, "en az bir arayuz raporlanmali"
    assert any(i.addresses for i in interfaces)
    assert all(i.name for i in interfaces)


@pytest.mark.parametrize("name", ["lo", "docker0", "br-dc1c73c834e1", "veth305278d", "wg0"])
def test_virtual_interfaces_are_recognised(name: str) -> None:
    assert network.is_virtual(name)


@pytest.mark.parametrize("name", ["eth0", "wlan0", "enp3s0", "end0"])
def test_physical_interfaces_are_not_flagged_virtual(name: str) -> None:
    assert not network.is_virtual(name)


def test_physical_interfaces_sort_above_container_bridges(monkeypatch: pytest.MonkeyPatch) -> None:
    """Seen on the real Pi: with docker running, br-*/veth* sorted alphabetically
    above wlan0 and pushed the only interesting interface to fourth place."""
    import collections

    Addr = collections.namedtuple("Addr", "family address netmask broadcast ptp")
    Stat = collections.namedtuple("Stat", "isup duplex speed mtu")
    Counter = collections.namedtuple("Counter", "bytes_sent bytes_recv")

    def addr(ip: str) -> Addr:
        return Addr(socket.AF_INET, ip, None, None, None)

    monkeypatch.setattr(
        network.psutil,
        "net_if_addrs",
        lambda: {
            "br-dc1c73c834e1": [addr("172.18.0.1")],
            "lo": [addr("127.0.0.1")],
            "veth305278d": [addr("169.254.1.1")],
            "wlan0": [addr("192.168.0.42")],
            "docker0": [addr("172.17.0.1")],
        },
    )
    monkeypatch.setattr(
        network.psutil, "net_if_stats", lambda: {
            name: Stat(True, "", 0, 1500)
            for name in ("br-dc1c73c834e1", "lo", "veth305278d", "wlan0", "docker0")
        }
    )
    monkeypatch.setattr(network.psutil, "net_io_counters", lambda pernic: {})

    assert [i.name for i in network.collect_interfaces()][0] == "wlan0"


def test_collect_static_tolerates_missing_proc_files() -> None:
    """None of /proc/net/route, /etc/resolv.conf or /proc/net/wireless exist on
    the Windows dev box - reading them must degrade, not raise."""
    gateway, dns, wireless = network.collect_static()
    assert isinstance(gateway, str)
    assert isinstance(dns, list)
    assert isinstance(wireless, list)


def test_network_info_over_the_wire(client: TestClient) -> None:
    ws = _authenticated(client)
    request = Envelope(type=MessageType.NETWORK_INFO, payload=NetworkInfoPayload())
    ws.send_json(request.model_dump(mode="json"))

    reply = ws.receive_json()
    assert reply["type"] == MessageType.NETWORK_INFO_RESULT.value
    assert reply["id"] == request.id
    assert reply["payload"]["hostname"]
    assert reply["payload"]["interfaces"]
